### ISSUE TITLE
Attack detection

### ISSUE THREAD

**Issue by novikov-alexander** [qiuxiang/aubiojs#14]
Hi, @qiuxiang! 
Thank you very much for such a good library.

I'm qurious can it detect consonants and sound attacks?
I would like to make a hand synchronization trainer for guitar players and would like to check the moment of time when a plector passes the string.

Maybe you've seen Melodyne application. It can distinguish between vowels and consonants in edit mode.
Maybe Aubio has that feature? I would be happy to port it from Aubio to Aubiojs if needed.

Kind regards,
Alexander

**Comment by qiuxiang** [comment]
I have only used a few functions of aubio, so I'm not sure if aubio can detect consonants and sound attacks.

**Comment by novikov-alexander** [comment]
I ported this feature via this PR: https://github.com/qiuxiang/aubiojs/pull/16
So, we can close this issue.
