### ISSUE TITLE
Pitch.html example not working on firefox, but I found a soultion :)

### ISSUE THREAD

**Issue by bertoncelj1** [qiuxiang/aubiojs#21]
Hi! Love the library. 

I just noticed that the pitch.html example doesnt work in firefox and I found out why.

The problem is that canvas is put over the audi controls so they are impossible to click. 
A simple fix would be to add to z-index to canvas css like that:

```
        canvas {
            position: absolute;
            top: 0;
            z-index: -1;
        }
```

**Comment by qiuxiang** [comment]
thx!
