### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by weathon** [qiuxiang/aubiojs#4]
https://qiuxiang.github.io/aubiojs/examples/tempo.html

**Comment by weathon** [comment]
这个demo的声音播放不了

**Comment by qiuxiang** [comment]
audio context 的权限机制后来更新了，暂时没有跟进，chrome 的话从 https://qiuxiang.github.io/aubiojs/examples/ 点进去是可以播放出声音的。

**Comment by weathon** [comment]
是的，从索引点进去可以，直接进去不行
